services:
  hh-applicant-tool:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    user: "${UID}:${GID}"
    environment:
      - UID=${UID}
      - GID=${GID}
    restart: always
